# Generated by Django 6.0 on 2025-12-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(verbose_name="название товара")),
                ("price", models.PositiveIntegerField(verbose_name="цена товара")),
            ],
            options={
                "verbose_name": "товар",
                "verbose_name_plural": "Товары",
            },
        ),
    ]
