# Generated by Django 6.0 on 2026-01-04 11:02

import apps.product.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.PositiveIntegerField(default=9, verbose_name='остаток на складе'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(apps.product.enums.ProductStatusEnum['AVAILABLE'], 'Доступен для продажи'), (apps.product.enums.ProductStatusEnum['ARCHIVED'], 'Архивный товар')], default=apps.product.enums.ProductStatusEnum['AVAILABLE'], verbose_name='статус товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=256, verbose_name='наименование товара'),
        ),
    ]
