# Generated by Django 6.0 on 2026-02-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_count_product_status_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='остаток на складе'),
        ),
    ]
